version: '3'
services:
  app:
    image: python:latest
    volumes:
      - ./docker/app/src:/src
    tty: true
    command: >
      bash -c "cd /src &&
      python /src/main.py"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: assignor_assignor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/db/conf.d:/etc/mysql/conf.d